# Site settings
title: Tao Blog
SEOTitle: 涛的博客 | Tao Blog
header-img: img/home-bg-art.jpg
email: lpt354290585@gmail.com
description: "前端与设计,这里是涛的个人博客"
keyword: "刘朋涛, 朋涛, Blog, Github, 博客, 互联网, 前端, 设计, 产品,  web, LPT, Tao, 朋涛的博客, Tao的博客, Tao Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "http://liupengtao.me"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# SNS settings
RSS: false
#weibo_username:     
#zhihu_username:     
github_username:    354290585
#twitter_username:   
#facebook_username:  
#linkedin_username:  



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: none
paginate: 10
exclude: ["less","futility","node_modules","Gruntfile.js","package.json","README.md","README.zh.md","baidu_verify_q4adWcdPGq.html"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate, jekyll-sitemap]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: tao-blog

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: '66c70ac633f32673893a4d3d4a8c1d26'

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一个正在进化中的程序猿..."
sidebar-avatar: /img/avatar-tao.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
# friends: [
#     {
#     #     title: "Su",
#     #     href: "http://su.gallery/"
#     # },{
#         title: "乱序",
#         href: "http://mida.re/"
#     },{
#         title: "前端外刊评论",
#         href: "http://qianduan.guru/"
#     },{
#         title: "天镶的博客",
#         href: "http://lingyu.wang/"
#     },{
#         title: "Luke 的自留地",
#         href: "http://hmqk1995.github.io"
#     },{
#         title: "Ebn's Blog",
#         href: "http://ebnbin.com/"
#     },{
#         title: "SmdCn's Blog",
#         href: "http://blog.smdcn.net"
#     },{
#         title: "解旻的博客",
#         href: "http://xieminis.me/"
#     },{
#         title: "DHong Say",
#         href: "http://dhong.co"
#     },{
#         title: "尹峰以为",
#         href: "http://ingf.github.io/"
#     },{
#         title: "前端神盾局",
#         href: "http://wepiaofei.github.io/blog/"
#     }
# ]
